### ISSUE TITLE
Не до конца разобрался с типом данных.

### ISSUE THREAD

**Issue by DonVietnam** [Alex8157/Tree#3]
https://github.com/Alex8157/Tree/blob/0f4b11332f501bf77efff962bff12b014b5e2ed1/script.js#L5-L8

Не совсем понял, что ты тут хотел сделать. Если проверить, что number, приведенный к числу является числом, а не NaN, то сделал это неверно. Вглядись в код  что и с чем ты сравниваешь. Причем потом у тебя твой же number как ни в чем не бывало идёт строкой дальше. parseInt - функция без побочного эффекта и переменную она никак не изменяет.

**Comment by Alex8157** [comment]
Сначала я хотел объяснить логику этого действия, но, честно признаться, ещё в прошлый раз понял, что этот кусок просто лишний, поэтому я его уберу
